#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# List of file extensions to be formatted
EXTENSIONS="c h cpp cpp cc"
CMAKEEXT="CMakeLists.txt *.cmake"

# Function to check if a file has a valid extension
is_valid_extension() {
    local file=$1
    for ext in $EXTENSIONS; do
        if [[ "$file" == *.$ext ]]; then
            return 0
        fi
    done
    return 1
}

# Function to check file is a CMakeLists
is_cmake_file() {
    local file=$1
    for ext in $CMAKEEXT; do
        if [[ "$file" == *.$ext ]]; then
            return 0
        fi
    done
    return 1
}

need_cmake_format()
{
  local file=$1
  return cmake-format -check $file
}

# Loop through staged files
for FILE in $(git diff --cached --name-only --diff-filter=ACM); do
  REPO_ROOT=$(pwd)
  if is_valid_extension "$FILE"; then
    # Apply clang-format
    clang-format -i "$FILE"
  fi
  if is_cmake_file "$REPO_ROOT/$FILE"; then
    if need_cmake_format "$REPO_ROOT/$FILE"; then
      cmake-format -i "$REPO_ROOT/$FILE"
    fi
  fi
  sed -i -e 's/[[:space:]]*$//' "$REPO_ROOT/$FILE"
  # Add the file back to the staging area
  git add "$FILE"
done

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff-index --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
